########################################################################
# Project: CI Expert 2026 - Parallel Binary Multiplier
# Id: run_dc.tcl
# Description: Logic Equivalence Check to Parallel Binary Multiplier to the test SAED32nm EDK
# Version: 2026-07-02
# Author: Arthur Ramalho
########################################################################

########################################################################
######################## FORMALITY LEC SETUP ###########################
########################################################################

########################################################################
# User variables setup
########################################################################

# Design name
set DESIGN      "parallel_binary_mult"

# Project directories
set PRJT_BASE   "/home/xmen-aluno/physical_design_arthur/project_parallel_binary_mult"
set DB_DIR      "${PRJT_BASE}/db"
set RTL_DIR     "${PRJT_BASE}/rtl"
set OUT_DIR     "${PRJT_BASE}/outputs"
set RPT_DIR     "${PRJT_BASE}/rpt"
set SDC_DIR     "${PRJT_BASE}/constraints"
set SVF_FILE    "${OUT_DIR}/${DESIGN}.svf"
set REF_RTL     "${RTL_DIR}/${DESIGN}.v"
set IMP_NETLIST "${OUT_DIR}/PRELAYOUT/${DESIGN}.v"

# TODO: fix this workaround
set design_libraries [glob ${DB_DIR}/*.db]
set db_index 0 
set LIB_DB [lindex $design_libraries $db_index]

########################################################################
# Create report directory
########################################################################
file mkdir ${RPT_DIR}/formality

########################################################################
# Formality Configuration 
########################################################################

# Recommended when the netlist was generated by Synopsys DC
set synopsys_auto_setup true

# Read SVF generated during synthesis
set_svf ${SVF_FILE}

########################################################################
# Read reference design
########################################################################

# Reference = RTL original design
# -r means reference side

read_db -r ${LIB_DB}

read_verilog -r ${REF_RTL}

set_top r:/WORK/${DESIGN}

########################################################################
# Read implementation (synthesized) design
########################################################################

# Implementation = synthesized mapped netlist
# -i means implementation side

read_db -i ${LIB_DB}

read_verilog -i ${IMP_NETLIST}

set_top i:/WORK/${DESIGN}

########################################################################
# Match and Verify
########################################################################

# Match reference and implementation points
match

# Generate reports after match
report_matched_points     > ${RPT_DIR}/formality/${DESIGN}_matched_points.rpt
report_unmatched_points   > ${RPT_DIR}/formality/${DESIGN}_unmatched_points.rpt

# Run equivalence checking
verify

# Final reports
report_passing_points     > ${RPT_DIR}/formality/${DESIGN}_passing_points.rpt
report_failing_points     > ${RPT_DIR}/formality/${DESIGN}_failing_points.rpt
report_aborted_points     > ${RPT_DIR}/formality/${DESIGN}_aborted_points.rpt
report_unverified_points  > ${RPT_DIR}/formality/${DESIGN}_unverified_points.rpt

########################################################################
# Exit
########################################################################

echo "*********************************************************************************"
echo "*********************************************************************************"
puts "\[VIRTUS-CC\] Logic Equivalence Check for Pre-Layout of the ${DESIGN} has been completed."
echo "*********************************************************************************"
echo "*********************************************************************************"
exit